name: "triton-recommender-retrieval"
platform: "tensorflow_savedmodel"  
parameters: {
key: "TF_SIGNATURE_DEF"
value: {
  string_value: "index"
  }
}
input: [
        {
            "name": "user_id",
            "data_type": "TYPE_STRING",
            "format": "FORMAT_NONE",
            "dims": [
                1
            ],
            "reshape": {
                "shape": []
            },
            "is_shape_tensor": false,
            "allow_ragged_batch": false,
            "optional": false
        }
    ],
output: [
        {
            "name": "output_1",
            "data_type": "TYPE_FP32",
            "dims": [
                5,
                1
            ],
            "label_filename": "",
            "is_shape_tensor": false
        }
    ]