name: "triton-recommender-ranking"
platform: "tensorflow_savedmodel"
max_batch_size: 0
input: [
        {
            "name": "movie_title",
            "data_type": "TYPE_STRING",
            "format": "FORMAT_NONE",
            "dims": [
                5
           ],
            "is_shape_tensor": false,
            "allow_ragged_batch": false,
            "optional": false
        },
        {
            "name": "user_id",
            "data_type": "TYPE_STRING",
            "format": "FORMAT_NONE",
            "dims": [
                1
            ],
            "reshape": {
                "shape": []
            },
            "is_shape_tensor": false,
            "allow_ragged_batch": false,
            "optional": false
        }
    ],
output: [
        {
            "name": "output_1",
            "data_type": "TYPE_FP32",
            "dims": [
                5,
                1
            ],
            "label_filename": "",
            "is_shape_tensor": false
        }
    ]