apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: mlpipelineui-backendconfig
  namespace: kubeflow
spec:
  timeoutSec: 40
  connectionDraining:
    drainingTimeoutSec: 60
  sessionAffinity:
    affinityType: CLIENT_IP

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mlpipelineui-ingress
  namespace: kubeflow
spec:
  rules:
  - http:
      paths:
      - path: /*
        pathType: ImplementationSpecific
        backend:
          service:
            name: ml-pipeline-ui
            port:
              number: 80
