apiVersion: mlops.seldon.io/v1alpha1
kind: Pipeline
metadata:
  name: chain
  namespace: seldon-mesh
spec:
  steps:
    - name: triton-recommender-retrieval
    - name: triton-recommender-ranking
      inputs:
      - triton-recommender-retrieval.inputs.INPUT0
      - triton-recommender-retrieval.outputs.OUTPUT0
      tensorMap: 
        triton-recommender-retrieval.outputs.OUTPUT0: INPUT1 #maps the outfrom from retrieval to the input for ranking
  output:
    steps:
    - triton-recommender-ranking